services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: articledb
    environment:
      POSTGRES_USER: hhuser
      POSTGRES_PASSWORD: hhpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  profanitydb:
    image: postgres:16
    environment:
      POSTGRES_USER: hhuser
      POSTGRES_PASSWORD: hhpass
    ports:
      - "5433:5432"
    volumes:
      - profanity-data:/var/lib/postgresql/data

  commentdb:
    image: postgres:16
    environment:
      POSTGRES_USER: hhuser
      POSTGRES_PASSWORD: hhpass
    ports:
      - "5434:5432"
    volumes:
      - comment-data:/var/lib/postgresql/data

  subscriberdb:
    image: postgres:16
    environment:
      POSTGRES_USER: hhuser
      POSTGRES_PASSWORD: hhpass
    ports:
      - "5435:5432"
    volumes:
      - subscriber-data:/var/lib/postgresql/data

  publisher-service:
    build: 
      context: ./publisher-service
      dockerfile: Dockerfile 
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - Zipkin__Endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "5000:80" 
    depends_on:
      - rabbitmq
      - zipkin

  profanity-service:
    build: 
      context: ./profanity-service
      dockerfile: Dockerfile 
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ProfanityDb=Host=profanitydb;Port=5432;Database=profanity_db;Username=hhuser;Password=hhpass
    ports:
      - "5096:80"

  comment-service:
    build: 
      context: ./comment-service
      dockerfile: Dockerfile 
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CommentDb=Host=commentdb;Port=5432;Database=comment_db;Username=hhuser;Password=hhpass
    ports:
      - "5097:80"

  subscriber-service:
    build: 
      context: ./subscriber-service
      dockerfile: Dockerfile 
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SubscriberDb=Host=subscriberdb;Port=5432;Database=subscriber_db;Username=hhuser;Password=hhpass
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "5098:80"
    volumes:
      - ./subscriber-service/appsettings.json:/app/appsettings.json

  newsletter-service:
    build: 
      context: ./newsletter-service
      dockerfile: Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Zipkin__Endpoint=http://zipkin:9411/api/v2/spans
    depends_on:
      - rabbitmq
      - zipkin


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus  


  article1: &article_base
    build: ./article-service
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=articledb;Port=5432;Database=articles;Username=hhuser;Password=hhpass
      - SERVICE_ID=article-1
    depends_on:
      - postgres
      - rabbitmq
      - zipkin
      - redis
    expose:
      - "80"

  article2:
    <<: *article_base
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=articledb;Port=5432;Database=articles;Username=hhuser;Password=hhpass
      - SERVICE_ID=article-2

  article3:
    <<: *article_base
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=articledb;Port=5432;Database=articles;Username=hhuser;Password=hhpass
      - SERVICE_ID=article-3

  loadbalancer:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - article1
      - article2
      - article3
    volumes:
      - ./article-service/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres-data:
  profanity-data:
  comment-data:
  subscriber-data: