events { }

http {
    upstream articleservice {
        server article1:80;
        server article2:80;
        server article3:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://articleservice;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}